### ISSUE TITLE
Need dessicated texture for dragons

### ISSUE THREAD

**Issue by isacmms** [Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Dwarves#21]
As per update 1.0.1982 all animals have their own dessicated texture and all CritterDessicated textures were removed (Things/Pawn/Animal/Dessicated/).

None of the core animals dessicated textures will fit a dragon to be reused like the others.
![dessicated_corpses](https://user-images.githubusercontent.com/12188263/43747386-bcae7a4a-99bf-11e8-93ec-cf771b2c2215.jpg)

**Comment by Ketrai** [comment]
I don't know how to grab one of the sprite files to use as reference, otherwise I could try my hand at making a dragon. I'd say the ones for mufalos, elephans and grizzly bears tends to come closest. Only the skull is a bit weird. And well, there's a lack of wing bones. The dragon sprite would be nice too. As rimworld typically models the corpses after the living animal, meaning legs and such are barely visible.

**Comment by jecrell** [comment]
Added a new Fire Drake dessicated sprite ^^
